// Mocks generated by Mockito 5.4.2 from annotations
// in boring_app/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:boring_app/business_logic/blocs/appbar/app_bar_cubit.dart'
    as _i2;
import 'package:flutter_bloc/flutter_bloc.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppBarState_0 extends _i1.SmartFake implements _i2.AppBarState {
  _FakeAppBarState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AppBarCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppBarCubit extends _i1.Mock implements _i2.AppBarCubit {
  MockAppBarCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppBarState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAppBarState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.AppBarState);

  @override
  _i3.Stream<_i2.AppBarState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i3.Stream<_i2.AppBarState>.empty(),
      ) as _i3.Stream<_i2.AppBarState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void expandAppBarWithAllFilters(double? finalAppBarHeight) =>
      super.noSuchMethod(
        Invocation.method(
          #expandAppBarWithAllFilters,
          [finalAppBarHeight],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetAppBar() => super.noSuchMethod(
        Invocation.method(
          #resetAppBar,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void emit(_i2.AppBarState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i4.Change<_i2.AppBarState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
