name: boring_app
description: A flutter portfolio project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  bloc_test: ^9.1.7
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  dio: ^5.5.0+1
  english_words: ^4.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.2
  mockito: ^5.4.4
  shared_preferences: ^2.2.3
  very_good_analysis: ^6.0.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0




flutter:

  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf



